= Antora UI
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://code.hampel-soft.com/dqmhconsortium/dqmh/docs-website-ui
:url-ci-pipelines: {url-project}/pipelines
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
:img-ci-status: {url-project}/badges/main/pipeline.svg

This project is used to build the UI of the CTI Website

=== Preamble

To support multiple languages, we build a ui for each langage to handle some contents that are not relying on Asccidoc sources.

See https://github.com/LabVIEWCommunityTraining/cti-documentation/issues/7[this issue] for more details

=== Prerequisites

To preview and bundle the UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-nodejs}[Node.js] (commands: `node` and `npm`)
* {url-gulp}[Gulp CLI] (command: `gulp`)

=== Preview the UI

The UI project is configured to preview offline.
The files in the [.path]_preview-src/_ folder provide the sample content that allows you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command in the desired language folder:

 $ gulp preview

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.
