name: Build website UIs
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
# build en website
    - name: Install Gulp locally to build the UI
      run: npm i gulp-cli ./en
    - name: Build en UI
      run: gulp bundle -f ./en/gulpfile.js
# build fr website
    - name: Install Gulp locally to build the UI
      run: npm i gulp-cli ./fr
    - name: Build fr UI
      run: gulp bundle -f ./fr/gulpfile.js
# download UIs
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ui-bundles
        path: "**/*.zip"
        exclude: "**/archive.zip"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4