name: Build website UIs
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Gulp for building the UI
      run: npm i -g gulp-cli
    - name: Install Gulp locally for building the UI
      run: npm i gulp-cli ./user-interface
    - name: Build UI
      run: gulp bundle -f ./en/gulpfile.js
    